/**
 * GENERATED by scripts/gen-ddl.ts from 0000_cool_joseph.sql, 0001_overjoyed_juggernaut.sql — do not edit.
 * A test asserts this stays identical to the migrations on disk.
 */

/**
 * Every migration, oldest first, each already split into single executable
 * statements. The index of a migration is its schema version minus one, which
 * is how `migrate` knows where an install left off.
 */
export const MIGRATIONS: { name: string; statements: string[] }[] =
[
  {
    "name": "0000_cool_joseph.sql",
    "statements": [
      "CREATE TABLE `account` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`household_id` text NOT NULL,\n\t`name` text NOT NULL,\n\t`kind` text NOT NULL,\n\t`opening_balance_minor` integer DEFAULT 0 NOT NULL,\n\t`opening_balance_on` text NOT NULL,\n\t`is_active` integer DEFAULT true NOT NULL,\n\t`sort_order` integer DEFAULT 0 NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`deleted_at` text,\n\tFOREIGN KEY (`household_id`) REFERENCES `household`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `account_household` ON `account` (`household_id`);",
      "CREATE TABLE `account_valuation` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`account_id` text NOT NULL,\n\t`as_of` text NOT NULL,\n\t`value_minor` integer NOT NULL,\n\t`note` text,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`deleted_at` text,\n\tFOREIGN KEY (`account_id`) REFERENCES `account`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `account_valuation_account` ON `account_valuation` (`account_id`,`as_of`);",
      "CREATE TABLE `category` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`household_id` text NOT NULL,\n\t`name` text NOT NULL,\n\t`kind` text NOT NULL,\n\t`parent_id` text,\n\t`is_person_facing` integer DEFAULT false NOT NULL,\n\t`archived` integer DEFAULT false NOT NULL,\n\t`sort_order` integer DEFAULT 0 NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`deleted_at` text,\n\tFOREIGN KEY (`household_id`) REFERENCES `household`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `category_household` ON `category` (`household_id`,`kind`);",
      "CREATE TABLE `household` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`deleted_at` text\n);",
      "CREATE TABLE `household_member` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`household_id` text NOT NULL,\n\t`user_id` text NOT NULL,\n\t`display_name` text NOT NULL,\n\t`role` text NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`deleted_at` text,\n\tFOREIGN KEY (`household_id`) REFERENCES `household`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE UNIQUE INDEX `household_member_unique` ON `household_member` (`household_id`,`user_id`);",
      "CREATE TABLE `outbox` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`table_name` text NOT NULL,\n\t`row_id` text NOT NULL,\n\t`op` text NOT NULL,\n\t`payload` text NOT NULL,\n\t`queued_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`attempts` integer DEFAULT 0 NOT NULL,\n\t`last_error` text\n);",
      "CREATE INDEX `outbox_queued` ON `outbox` (`queued_at`);",
      "CREATE TABLE `person` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`household_id` text NOT NULL,\n\t`name` text NOT NULL,\n\t`relation` text,\n\t`member_user_id` text,\n\t`archived` integer DEFAULT false NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`deleted_at` text,\n\tFOREIGN KEY (`household_id`) REFERENCES `household`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `person_household` ON `person` (`household_id`);",
      "CREATE TABLE `sync_state` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`last_pulled_at` text,\n\t`device_id` text NOT NULL\n);",
      "CREATE TABLE `txn` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`household_id` text NOT NULL,\n\t`type` text NOT NULL,\n\t`occurred_on` text NOT NULL,\n\t`amount_minor` integer NOT NULL,\n\t`tips_minor` integer DEFAULT 0 NOT NULL,\n\t`fee_minor` integer DEFAULT 0 NOT NULL,\n\t`account_id` text NOT NULL,\n\t`counter_account_id` text,\n\t`category_id` text,\n\t`person_id` text,\n\t`note` text,\n\t`is_opening` integer DEFAULT false NOT NULL,\n\t`created_by` text,\n\t`legacy_row_id` integer,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`deleted_at` text,\n\tFOREIGN KEY (`household_id`) REFERENCES `household`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`account_id`) REFERENCES `account`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`counter_account_id`) REFERENCES `account`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`category_id`) REFERENCES `category`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`person_id`) REFERENCES `person`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `txn_household_date` ON `txn` (`household_id`,`occurred_on`);",
      "CREATE INDEX `txn_account` ON `txn` (`account_id`);",
      "CREATE INDEX `txn_category` ON `txn` (`category_id`);",
      "CREATE INDEX `txn_person` ON `txn` (`person_id`);"
    ]
  },
  {
    "name": "0001_overjoyed_juggernaut.sql",
    "statements": [
      "PRAGMA foreign_keys=OFF;",
      "CREATE TABLE `__new_outbox` (\n\t`table_name` text NOT NULL,\n\t`row_id` text NOT NULL,\n\t`queued_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\tPRIMARY KEY(`table_name`, `row_id`)\n);",
      "INSERT INTO `__new_outbox`(\"table_name\", \"row_id\", \"queued_at\") SELECT \"table_name\", \"row_id\", \"queued_at\" FROM `outbox`;",
      "DROP TABLE `outbox`;",
      "ALTER TABLE `__new_outbox` RENAME TO `outbox`;",
      "PRAGMA foreign_keys=ON;",
      "ALTER TABLE `household` ADD `invite_code` text;",
      "ALTER TABLE `household_member` ADD `email` text;",
      "ALTER TABLE `sync_state` ADD `user_id` text;"
    ]
  }
]
