/**
 * Copies the generated SQLite migrations into src/db/ddl.ts so the app can run
 * them without Metro needing a .sql transformer. Re-run after drizzle-kit
 * generate; src/db/local.test.ts fails if this file and the migrations drift.
 *
 * They are emitted one group per file rather than as a single blob, because an
 * install that already ran 0000 must run only what came after it.
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'

const dir = path.join('drizzle', 'sqlite')
const files = readdirSync(dir).filter((f) => f.endsWith('.sql')).sort()

const migrations = files.map((file) => ({
  name: file,
  statements: readFileSync(path.join(dir, file), 'utf8')
    .split('--> statement-breakpoint')
    .map((s) => s.trim())
    .filter((s) => s.length > 0),
}))

const out = `/**
 * GENERATED by scripts/gen-ddl.ts from ${files.join(', ')} — do not edit.
 * A test asserts this stays identical to the migrations on disk.
 */

/**
 * Every migration, oldest first, each already split into single executable
 * statements. The index of a migration is its schema version minus one, which
 * is how \`migrate\` knows where an install left off.
 */
export const MIGRATIONS: { name: string; statements: string[] }[] =
${JSON.stringify(migrations, null, 2)}
`
writeFileSync(path.join('src', 'db', 'ddl.ts'), out)
console.log('wrote src/db/ddl.ts:', files.join(', '))
