/**
 * Builds supabase/setup.sql — the one file to paste into the Supabase SQL
 * editor — out of the generated Postgres migrations plus the hand-written
 * policies.
 *
 * Generating it rather than maintaining it by hand is the point: the schema
 * half can only ever be what drizzle produced from `schema.pg.ts`, so the
 * database the phone talks to cannot quietly diverge from the one the app was
 * built against. `src/db/supabase-sql.test.ts` fails if this file is stale.
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'

const HEADER = `-- SpendLogX — Supabase setup
--
-- GENERATED by scripts/gen-supabase-sql.ts. Do not edit: change
-- src/db/schema.pg.ts (then \`npm run db:generate\`) or supabase/policies.sql,
-- and re-run \`npm run supabase:sql\`.
--
-- Paste the whole file into the Supabase SQL editor and run it once. It is
-- safe to run again: every statement is written to be repeatable.
`

export function build(): string {
  const dir = path.join('drizzle', 'pg')
  const files = readdirSync(dir).filter((f) => f.endsWith('.sql')).sort()

  const schema = files
    .map((file) => {
      const sql = readFileSync(path.join(dir, file), 'utf8')
        .split('--> statement-breakpoint')
        .map((s) => s.trim())
        .filter((s) => s.length > 0)
        // Re-running must not fail on what is already there. Drizzle writes
        // migrations for a tracked database; this file has no such luxury.
        .map(repeatable)
        .join('\n')
      return `-- ${file}\n${sql}`
    })
    .join('\n\n')

  const policies = readFileSync(path.join('supabase', 'policies.sql'), 'utf8').trim()

  return `${HEADER}\n${schema}\n\n${policies}\n`
}

/**
 * The same statement, written so a second run is a no-op.
 *
 * Postgres has `IF NOT EXISTS` for tables and indexes but not for constraints
 * or columns added by `ALTER TABLE`, so those are wrapped in a block that
 * swallows only the "already there" error and nothing else.
 */
function repeatable(statement: string): string {
  const sql = statement.replace(/;$/, '')

  if (/^CREATE TABLE "/i.test(sql)) {
    return `${sql.replace(/^CREATE TABLE /i, 'CREATE TABLE IF NOT EXISTS ')};`
  }
  if (/^CREATE (UNIQUE )?INDEX "/i.test(sql)) {
    return `${sql.replace(/^CREATE (UNIQUE )?INDEX /i, (m) => `${m}IF NOT EXISTS `)};`
  }
  if (/^ALTER TABLE .* ADD COLUMN /i.test(sql)) {
    return `${sql.replace(/ADD COLUMN /i, 'ADD COLUMN IF NOT EXISTS ')};`
  }
  if (/^ALTER TABLE .* ADD CONSTRAINT /i.test(sql)) {
    return `do $$ begin\n  ${sql};\nexception when duplicate_object then null;\nend $$;`
  }
  return `${sql};`
}

if (process.argv[1]?.endsWith('gen-supabase-sql.ts')) {
  writeFileSync(path.join('supabase', 'setup.sql'), build())
  console.log('wrote supabase/setup.sql')
}
