/**
 * Copies the generated SQLite migration into src/db/ddl.ts so the app can run
 * it without Metro needing a .sql transformer. Re-run after drizzle-kit
 * generate; src/db/local.test.ts fails if this file and the migration drift.
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'

const dir = path.join('drizzle', 'sqlite')
const files = readdirSync(dir).filter((f) => f.endsWith('.sql')).sort()
const sql = files.map((f) => readFileSync(path.join(dir, f), 'utf8')).join('\n')

const out = `/**
 * GENERATED by scripts/gen-ddl.ts from ${files.join(', ')} — do not edit.
 * A test asserts this stays identical to the migration on disk.
 */

export const DDL = ${JSON.stringify(sql)}

/** The migration split into single executable statements. */
export const DDL_STATEMENTS: string[] = DDL.split('--> statement-breakpoint')
  .map((s) => s.trim())
  .filter((s) => s.length > 0)
`
writeFileSync(path.join('src', 'db', 'ddl.ts'), out)
console.log('wrote src/db/ddl.ts:', files.join(', '))
